# Dependabot config for website and cli security updates

version: 2
updates:
  # website package
  - package-ecosystem: 'npm'
    directory: '/packages/website/'
    schedule:
      interval: 'weekly'
    # Only do security updates
    open-pull-requests-limit: 0

  # Cli package
  - package-ecosystem: 'npm'
    directory: '/packages/create-starter/'
    schedule:
      interval: 'weekly'
    # Only do security updates
    open-pull-requests-limit: 0
