# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: graphql-serverless-contentful

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs16.x

# The `functions` block defines what code to deploy
functions:
  graphql:
    handler: src/handlers/graphql.server
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  healthcheck:
    handler: src/handlers/healthcheck.handler
    events:
      - http:
          path: healthcheck
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

useDotenv: true
