version: '3'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./postgres.db.env

  redis_cache:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - cache:/var/lib/redis
      - ./misc/cache_conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  redis_queue:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6479:6379'
    volumes:
      - queue:/var/lib/redis
      - ./misc/queue_conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  database:
  cache:
  queue:
