name: Feature request
description: Suggest an idea for this project
labels: New Issue, feature
body:
  - type: markdown
    attributes:
      value: Thank you for submitting an issue. We appreciate your feedback and contributions to this repository. However, before submitting, please make sure you can fill out all the details below in the template. If your issue is a "how to" or feature enhancement discussion, please go to the discussions tab and submit there instead.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Addtional context
      description: Add any other context or screenshots about the feature request here.
