name: Deno lint and test
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up latest Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Deno formatter check
        run: deno fmt --check
      - name: Deno lint check
        run: deno lint
      - name: Deno run tests
        run: deno test
