# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular Apollo Tailwind CI

on:
  push:
    branches: [main]
    paths:
      - 'starters/angular-apollo-tailwind/**'
  pull_request:
    branches: [main]
    paths:
      - 'starters/angular-apollo-tailwind/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: ''

      - name: Install dependencies
        run: npm i
        working-directory: starters/angular-apollo-tailwind

      - name: Lint files
        run: npm run lint
        working-directory: starters/angular-apollo-tailwind

      - name: Build Project
        run: npm run build
        working-directory: starters/angular-apollo-tailwind

      - name: Test Project
        run: npm test
        working-directory: starters/angular-apollo-tailwind
