# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nuxt2 Pinia Tailwind CI

on:
  push:
    branches: [main]
    paths:
      - 'starters/nuxt2-pinia-tailwind/**'
  pull_request:
    branches: [main]
    paths:
      - 'starters/nuxt2-pinia-tailwind/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: 'starters/nuxt2-pinia-tailwind/package.json'
          cache: ''

      - name: Install dependencies
        run: npm i
        working-directory: starters/nuxt2-pinia-tailwind

      - name: Lint files
        run: npm run lintfix
        working-directory: starters/nuxt2-pinia-tailwind

      - name: Build Project
        run: npm run build
        working-directory: starters/nuxt2-pinia-tailwind

      - name: Test Project
        run: npm run test
        working-directory: starters/nuxt2-pinia-tailwind
